# Generated by Django 4.2.16 on 2024-10-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('home', '0003_homepage_custom_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
