# Generated by Django 4.2.16 on 2024-10-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0002_blogdetail_image'),
        ('home', '0005_homepage_cta_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpages.blogdetail'),
        ),
    ]
